### ISSUE TITLE
Request for Assistance: Plotting White Line Borders on Hippocampal Mid-thickness Surface

### ISSUE THREAD

**Issue by debinz** [Bradley-Karat/Hippo_Macro_Micro#1]
Hello Bradley!

I wanted to express my gratitude for sharing the valuable codes associated with your insightful paper. Your work has been immensely helpful in my research.

I am writing to seek your guidance on a specific aspect of your code. I am particularly interested in plotting one metric on the hippocampal mid-thickness surface with subfield borders delineated by white lines, akin to the visually striking Figures 3, 5, and 7 in your paper. However, I couldn't locate this specific functionality in either your repository or Jordan DeKraker's hippunfold_toolbox.

While the hippunfold_toolbox is able to display borders with several points, I am specifically looking to implement white line borders. Could you please share the relevant code or offer any advice on how to achieve this effect? Your expertise in this matter would be immensely valuable to my project.

Thank you once again for your contribution to the field, and I appreciate your time and consideration in addressing my query. I look forward to hearing from you at your earliest convenience.

Warm regards,
Debin

**Comment by Bradley-Karat** [comment]
Hi Debin,

Thanks, I am really glad you found this code helpful!

Unfortunately, their is no straightforward way (at least from what I have tried) to plot lines on top of a Matlab patch object that is not a normal grid, particularly because the subfield borders in that case have to be a patch themselves also. I actually made a hand-drawn template of the subfield lines you see in the paper and saved that as a .svg which I then copied onto all unfolded space plots. Would be happy to share this .svg with you if that would help.

The other option which also works nicely but may require a bit more work would be to resample your metric data to the "unfoldiso" density from your current density (0p5mm, 1mm, 2mm...). This can be done with the hippunfold_toolbox (the `density_interp` command in the `utils.py` file). The unfoldiso space consists of 32004 vertices, which make up a 254 x 126 grid. When your metric is in this space, it becomes much easier to plot the subfield lines. The same plotting script here can be used (as long as you have folded and unfolded surfaces at the same unfoldiso density), then what you could do is the following:
`unfL = gifti('sub-01_hemi-L_space-unfolded_den-unfoldiso_subfields.label.gii').cdata; %load in unfoldiso subfields`
`unfL = reshape(unfL,[254,126]) %reshape to grid`
`[Gmag,Gdir] = imgradient(unfL) %Find gradient of subfields`
`Gmag(Gmag>0) = 1 %Border pixels=1`

Then at the end of the plotting script you can add:
`hold on`
`imcontour(Gmag, 'w')`

This should give you the plot you are looking for. 
Let me know if that helps or if you have any other questions!

All the Best,
Brad

**Comment by debinz** [comment]
Hi Brad,

Thank you so much for your detailed explanation and for offering to share the .svg file with me (you can email it to me at debin_zeng@163.com if you want). I really appreciate your help!

I will try out the options you suggested, starting with resampling my metric data to the "unfoldiso" density using the hippunfold_toolbox. The additional steps you provided for plotting the subfield lines are clear, and I will incorporate them into my script.

I will definitely reach out if I have any further questions or need any more assistance. Thanks again for your support!

Best regards,
Debin
